const fs = require("fs"), path = require("path");
const base = process.argv[2];
const MAP = {
  send: "arrow-up", plane: "paper-plane-tilt", plus: "plus", reply: "arrow-bend-up-left", smile: "smiley", pin: "push-pin", mapPin: "map-pin",
  calendar: "calendar-blank", calendarPlus: "calendar-plus", users: "users-three", user: "user", userPlus: "user-plus", userCheck: "user-check",
  check: "check", checkCircle: "check-circle", x: "x", xCircle: "x-circle", chevronRight: "caret-right", chevronLeft: "caret-left", chevronDown: "caret-down", chevronUp: "caret-up",
  updown: "caret-up-down", search: "magnifying-glass", more: "dots-three", moreV: "dots-three-vertical", edit: "pencil-simple", file: "file-text", image: "image",
  link: "link-simple", download: "download-simple", chart: "chart-bar", poll: "chart-bar-horizontal", settings: "gear-six", flag: "flag", bell: "bell", bellOff: "bell-slash",
  clock: "clock", book: "book-open", shield: "shield-check", hash: "hash", arrowDown: "arrow-down", arrowRight: "arrow-right", logout: "sign-out", camera: "camera",
  paste: "clipboard-text", info: "info", history: "clock-counter-clockwise", sun: "sun", moon: "moon", bookmark: "bookmark-simple", chats: "chats-circle", chat: "chat-circle",
  board: "push-pin-simple", tasks: "list-checks", checkSquare: "check-square", square: "square", ticket: "ticket", store: "storefront", lost: "magnifying-glass-plus",
  eye: "eye", eyeOff: "eye-slash", block: "prohibit", trash: "trash", copy: "copy", external: "arrow-square-out", keyboard: "keyboard", command: "command",
  funnel: "funnel", grad: "graduation-cap", house: "house", bolt: "lightning", wave: "hand-waving", lock: "lock-simple", note: "note", exam: "exam", warning: "warning",
  heart: "heart", fire: "fire", play: "play", pause: "pause", envelope: "envelope-simple", megaphone: "megaphone", star: "star", sparkle: "sparkle", door: "door-open",
  coffee: "coffee", sliders: "sliders-horizontal", question: "question", rows: "rows", grid: "squares-four", tag: "tag", target: "target", trend: "trend-up", confetti: "confetti",
};
const inner = (f) => fs.readFileSync(f, "utf8").replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
const out = {};
for (const [k, n] of Object.entries(MAP)) {
  const r = path.join(base, "regular", n + ".svg"), f = path.join(base, "fill", n + "-fill.svg");
  if (!fs.existsSync(r)) { console.error("missing", n); continue; }
  out[k] = [inner(r), fs.existsSync(f) ? inner(f) : inner(r)];
}
const js = `// Phosphor Icons 2.1.1 (MIT, @phosphor-icons/core): regular (1.5px stroke at 24px, the SF Symbols match)
// in lists and toolbars, fill when selected — Apple's SF Symbols rule. Generated by test/gen-icons; do not edit by hand.
const PH = ${JSON.stringify(out)};
// Community Notes' radiating mark for AI-drafted content (no sparkles, per DESIGN.md).
const AI_MARK = '<circle cx="128" cy="128" r="30"/><circle cx="128" cy="128" r="68" fill="none" stroke="currentColor" stroke-width="16" stroke-dasharray="26 22"/><circle cx="128" cy="128" r="104" fill="none" stroke="currentColor" stroke-width="12" stroke-dasharray="14 26"/>';
function iconSvg(name, size, fill) {
  const s = size || 20;
  const body = name === "ai" ? AI_MARK : (PH[name] || PH.question)[fill ? 1 : 0];
  return '<svg xmlns="http://www.w3.org/2000/svg" width="' + s + '" height="' + s + '" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true">' + body + "</svg>";
}
`;
fs.writeFileSync(process.argv[3], js);
console.log("icons:", Object.keys(out).length, "bytes:", js.length);
